env:
  global:
    # DOCKER_EMAIL
    - secure: "qokEL3Dg12uIT5EM9wRXTfSwebc0eaKMB0uedYKF3XttJjHgkwQ8zsYd23HG0jnt8InDUzLhWekQzZW5Q1BTQc8aMQz+V2J8WIAXJmdMwcEXCuyyWtOwoMGm+JMKOWvwH04gos5YBQK7XkKd5uvLWo1A+9ok0CX71vARewQ42V1/SA/EmaQQa4MZ1fcE2+mNidGw2ONEwzp1N8DFnw1NMrt8bP9bYYSdUgW99/5hzg6RHR9kZnFPKhCeMtm7pNaPn2k6w7xg7nVpKJchqa93W42zYb40OpqiQ6H9wW44yN9yZkIuHZA7U6rdH1xJOpjXyACTeqdoxtgS4EcSGXxt2cPSq8gaBUNHx8Cpyb7nHqpi4/DWUBFtPO70fWv1ZxIx/pRXZ0Slpr+ANWrlipyYOtPzPiqqJSGEeXsXKWZykp0GhWTLS8Pe4FbhoPPcYq8JGibPPKHfenswHKGI9MiSbjXWJt25N4k4LaE45lR61m4f4HhNT6R0qlWIAgC6eo7xqtbaU6KymBWmuDGAwV66MV3f6dd/RLZvM3k04OZynE6WmYEhEvHsfQ/BKF67MbF8Jjk2bz+a3XHPoLaODpsGP+dJylrc5Ci6aJwukfxYvjHsTxX+NgemMihlhThydXEOc2z3Ye/D7tGvVzkvh6cWx2+s+3xId3Mr9fe9f7IWEkE="
    # DOCKER_USER
    - secure: "RI+qFojXg8Yb3sVJABZTBo90Z8F/JjC8B6WBO/1P+2vkUfKkhdnrAzePoMheWFXfLuGdAYpgWfCUM6NY4WGdEnC4dR4NxjdpNXoscHPOWUDe2NgbKCop8jOJ9lksnuhmHpMFNo5zQshCfsPNBEIURiemg16tIJ1DtBNaWs4Xgm7lmV5rQ1Ucz6cddCw8FCIduULbgUbPBtiuLiQ3ExZW+spdP9iRvZUiXDA8qoCCFAzm6sjPYcS8EbryCnRlu1zu4Rr4m+9DUvcs9Rwbd+g9XvWUh0Be1dKRYHMzTgvZjdnV5WtO+TGIQuPb97u19nL9w8CNaqpev4XzoXpiDTmKA4GIXmZNPsiLUoaTtwXXC+GdBM2J2qfjQ+9kIBXGdp2BDIdI9haC04URA+EkoYB5HtIRq8qbRbtfQg/Vtn2MLZKQ3ndgNSI7Y+Q3n1VyGuhMtFyBz975jBm1QgmsxyHrxUPtXCliGJHVu3dCpU9OK5Fv3fttop5YpVy8bF2WB1C9RoN5fK105B6yowHeU96ckw99baI2c1Z1MiRw9er+ogs2Ii+v6GuGkB76BtkudcsHVz2PP3kysNcveowmk8y+P6Z2+TsH5yvOu9mxZRGp/Im48W48uTnmg6RxWjh26ZfOD+Mts19YhTQWyVGATozpYAPrgeJyGvThkBFa7w+9TEc="
    # DOCKER_PASS
    - secure: "S4ge+eD5ywmFIhgmKSiRPJWtjCNBZ14vG5yJM1bEOGpfeK/04TRAP2/Bwf2yyHxf/pJI0LYJp909MQWSqjOYP168unhvmQWn6GopnZ2GUqQzKTGKk9xv1Jn2acevmJigsPpvHrx2a3FsEg1HPejjrR1FIlZQhSYQEFBiSwEiwpgaM5EFLSNwYtlB372M6czJxdiClxXOuzRaTrIRr7p7yem0kEn1pCAxlHH5y9UsPn1s40gyGLp6XPDeZHxXcJuJOHmS9Eb4CwWqKnNCuDBMafCv0CS5qvrlK2Kn2ep+p/W5tXQ/HlbAzppernTN2ErgF/I5QdUR1ua7BxaSDsDQNdRC4iZ77P6GrImyjKAWTw0ikORxGYqhQ0Z5AsmCEcgS446s29L82owx/ft/f24eS+dN30J7awduryOAEWnooqE85RIVrvRIWlsiJ07go+COWUZyQWew3YTuWKaE/huTl+P+j3uGAfL+4uo57tAMR3LE60n9vbJlfOhLY9lqAV75E6UIRdGiOH93vfzmntuBoTSrSsktSdxP43u8hA6bQ2RFItry6c5FckSstKAFLQu2yFTOk4WRYzzCXQMtI92pABNRZOyosOGQw+pIh+LVZ5WSppFXGy90+pmp/8Jq+86h4qyCJ0cNZ3C1xextCkbdd7Ssw5bpTr4TEJvABJPxFs8="

language: node_js
node_js:
  - '8'

sudo: required
services:
  - docker

install:
  - npm install

script:
  - npm run lint
  - docker-compose pull
  - docker-compose up -d
  - sleep 10
  - npm test

after_success:
  - npm run coveralls
  # No docker push on pull requests
  - if [ "$TRAVIS_PULL_REQUEST" == "true" ]; then exit; fi
  - docker login -u $DOCKER_USER -p $DOCKER_PASS
  - export REPO=koumoul/data-fair
  - export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo $TRAVIS_BRANCH ; fi`
  - docker build -f Dockerfile -t $REPO:$TAG .
  - docker push $REPO
