version: '3'
services:
  es:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.1.1
    ports:
      - 9200:9200
      - 9300:9300
    environment:
      - discovery.type=single-node
  mongo:
    image: mvertes/alpine-mongo:3.4.9-0
    ports:
      - 27017:27017
  simple-directory:
    image: koumoul/simple-directory:latest
    network_mode: host
    ports:
      - 8080
      - 1080
    environment:
      - NAMES_WEBHOOKS=["http://localhost:5600/api/v1/owner-names?key=dev_secret"]
      - PUBLIC_URL=http://localhost:8080
      - MAILDEV_ACTIVE=true
      - STORAGE_TYPE=file
      - NUXT_BUILD_BLOCKING=false
    volumes:
      - ./test/resources/users.json:/webapp/data/users.json
      - ./test/resources/organizations.json:/webapp/data/organizations.json
