version: '3'
services:
  es:
    profiles:
      - dev
      - test
    image: ghcr.io/data-fair/elasticsearch:7.17.1
    ports:
      - 9200:9200
      - 9300:9300
    environment:
      - discovery.type=single-node
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data
  mongo:
    profiles:
      - dev
      - test
    image: mongo:4.2
    ports:
      - 27017:27017
    volumes:
      - mongo-data:/data/db
  sd:
    profiles:
      - dev
      - test
    image: ghcr.io/data-fair/simple-directory:master
    network_mode: host
    environment:
      - DEBUG=webhooks
      - ADMINS=["alban.mouton@koumoul.com", "superadmin@test.com"]
      - 'IDENTITIES_WEBHOOKS=[{"base": "http://localhost:5600/api/v1/identities", "key": "dev_secret"}]'
      - PUBLIC_URL=http://localhost:5600/simple-directory
      - MAILDEV_ACTIVE=true
      - STORAGE_TYPE=file
      #- STORAGE_TYPE=mongo
      - STORAGE_MONGO_URL=mongodb://localhost:27017/simple-directory
      - NUXT_BUILD_BLOCKING=false
      - LIST_ENTITIES_MODE=anonymous
      - NO_UI=${NO_UI}
      - AUTHRATELIMIT_ATTEMPTS=200
      - DEFAULT_MAX_CREATED_ORGS=10
      - ANONYMOUS_ACTION_NOT_BEFORE=1s
    volumes:
      - ./test/resources/users.json:/webapp/data/users.json
      - ./test/resources/organizations.json:/webapp/data/organizations.json

  openapi-viewer:
    profiles:
      - dev
    image: koumoul/openapi-viewer:1
    ports:
      - 5680:8080

  capture:
    profiles:
      - dev
    image: koumoul/capture:master
    network_mode: host
    shm_size: '1gb'
    environment:
      - PORT=8087
      - DEBUG=capture
      - PUBLIC_URL=http://localhost:5600/capture

  thumbor:
    profiles:
      - dev
    image: apsl/thumbor:6.4.2
    network_mode: host
    environment:
      - SECURITY_KEY=thumborkey
      - STORAGE_EXPIRATION_SECONDS=600
      - MAX_AGE=600

  notify:
    profiles:
      - dev
    image: ghcr.io/data-fair/notify:master
    network_mode: host
    environment:
      - PORT=8088
      - PUBLIC_URL=http://localhost:5600/notify
      - WS_PUBLIC_URL=ws://localhost:5600/notify
      - DIRECTORY_URL=http://localhost:5600/simple-directory
      - SECRET_NOTIFICATIONS=secret-notifications
      - SECRET_SENDMAILS=secret-sendmails

volumes:
  elasticsearch-data:
  mongo-data:
