version: '3'
services:
  es:
    image: koumoul/data-fair-elasticsearch:7.0.0
    ports:
      - 9200:9200
      - 9300:9300
    environment:
      - discovery.type=single-node
  mongo:
    image: mongo:4.1
    ports:
      - 27017:27017
  sd:
    image: koumoul/simple-directory:1
    network_mode: host
    ports:
      - 8080
      - 1080
    environment:
      - DEBUG=webhooks
      - ADMINS=["alban.mouton@koumoul.com", "superadmin@test.com"]
      - 'IDENTITIES_WEBHOOKS=[{"base": "http://localhost:5600/api/v1/identities", "key": "dev_secret"}]'
      - PUBLIC_URL=http://localhost:5600/simple-directory
      - MAILDEV_ACTIVE=true
      - STORAGE_TYPE=file
      #- STORAGE_TYPE=mongo
      - STORAGE_MONGO_URL=mongodb://localhost:27017/simple-directory
      - NUXT_BUILD_BLOCKING=false
      - LIST_ENTITIES_MODE=anonymous
      - NO_UI=${NO_UI}
    volumes:
      - ./test/resources/users.json:/webapp/data/users.json
      - ./test/resources/organizations.json:/webapp/data/organizations.json

  openapi-viewer:
    image: koumoul/openapi-viewer:1
    ports:
      - 5680:8080

  capture:
    image: koumoul/capture:master
    network_mode: host
    shm_size: '1gb'
    environment:
      - PORT=8087
      - DEBUG=capture
      - PUBLIC_URL=http://localhost:5600/capture

  thumbor:
    image: apsl/thumbor:6.4.2
    network_mode: host
    environment:
      - SECURITY_KEY=thumborkey
      - STORAGE_EXPIRATION_SECONDS=600
      - MAX_AGE=600
