version: '2'
services:
  es:
    image: elasticsearch:5.6.3-alpine
    ports:
      - 9200:9200
  mongo:
    image: mvertes/alpine-mongo:3.4.9-0
    ports:
      - 27017:27017
  simple-directory:
    image: koumoul/simple-directory:0.1.0
    ports:
      - 5700:8080
    environment:
      - PUBLIC_URL=http://localhost:5700
    volumes:
      - ./test/resources/users.json:/webapp/resources/users.json
      - ./test/resources/organizations.json:/webapp/resources/organizations.json
