version: '3'
services:
  es:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.1.1
    ports:
      - 9200:9200
      - 9300:9300
    environment:
      - discovery.type=single-node
  mongo:
    image: mvertes/alpine-mongo:3.4.9-0
    ports:
      - 27017:27017
  simple-directory:
    image: koumoul/simple-directory:0.2.0
    ports:
      - 5700:8080
    environment:
      - PUBLIC_URL=http://localhost:5700
      # For virtual box debugging
      # - PUBLIC_URL=http://10.0.2.2:5700
    volumes:
      - ./test/resources/users.json:/webapp/resources/users.json
      - ./test/resources/organizations.json:/webapp/resources/organizations.json
