version: '3'
services:
  es:
    image: koumoul/data-fair-elasticsearch:latest
    ports:
      - 9200:9200
      - 9300:9300
    environment:
      - discovery.type=single-node
  mongo:
    image: mvertes/alpine-mongo:4.0.3-0
    ports:
      - 27017:27017
  sd:
    image: koumoul/simple-directory:latest
    network_mode: host
    ports:
      - 8080
      - 1080
    environment:
      - ADMINS=["alban.mouton@koumoul.com"]
      - NAMES_WEBHOOKS=["http://localhost:5600/api/v1/owner-names?key=dev_secret"]
      - PUBLIC_URL=http://localhost:8080
      - MAILDEV_ACTIVE=true
      - STORAGE_TYPE=file
      - NUXT_BUILD_BLOCKING=false
      - LIST_ENTITIES_MODE=anonymous
    volumes:
      - ./test/resources/users.json:/webapp/data/users.json
      - ./test/resources/organizations.json:/webapp/data/organizations.json

  openapi-viewer:
    image: koumoul/openapi-viewer:0.8.0
    ports:
      - 5680:8080
