remote_theme: mmistakes/minimal-mistakes
name: Koumoul
title: Data FAIR
description: Rendez vos données Faciles à trouver, Accessibles, Interopérables, Réutilisables.

locale: "fr-FR"

# Plugins (previously gems:)
plugins:
  - jekyll-remote-theme

minimal_mistakes_skin: "air" # "default", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum" "sunrise"
include:
  - _pages

defaults:
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: false
      read_time: true
      share: true
      toc: true
      toc_label: "Table des matières"

repository: "koumoul-dev/data-fair"
search: true

twitter:
  username: &twitter "Koumoul_fr"
social:
  type: Organization
  name:  Koumoul
  links:
    - "https://twitter.com/Koumoul_fr"
    # - "https://facebook.com/yourFacebook"
    # - "https://instagram.com/yourProfile"
    # - "https://www.linkedin.com/in/yourprofile"
    # - "https://plus.google.com/your_profile"

author:
  name   : "Koumoul"
  avatar : "/assets/images/koumoul.png"
  bio    : "La donnée accessible"
  email  : contact@koumoul.com
  uri    : "https://koumoul.com"
  github : koumoul-dev
  gitlab : koumoul
  twitter: *twitter
