remote_theme: mmistakes/minimal-mistakes
title: Accessible-Data - Documentation
description: Partagez et enrichissez facilement vos données pour pouvoir les utiliser dans des applications dédiées

# Plugins (previously gems:)
plugins:
  - jekyll-remote-theme

minimal_mistakes_skin: "air" # "default", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum" "sunrise"
