remote_theme: minimal-mistakes-jekyll
title: Accessible-Data - Documentation
description: Partagez et enrichissez facilement vos données pour pouvoir les utiliser dans des applications dédiées

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-remote-theme
