name: Publish documentation

on:
  push:
    branches: [ 'master' ]
    tags: [ 'v*.*.*' ]
  pull_request:

jobs:
  publish-doc:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x]
    steps:
      - run: echo $GITHUB_REF
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm i
      - run: export MAJOR=$(./node_modules/.bin/semver-extract --major --branch $GITHUB_REF)
      - run: DOC_BASE=/data-fair/$MAJOR/ npm run build-doc
      - run : |
          git config --global user.email "github-actions@koumoul.com"
          git config --global user.name "github-actions"
      - run: ./node_modules/.bin/gh-pages-multi deploy -v -r https://${GITHUB_TOKEN}@github.com/koumoul-dev/data-fair.git -s doc-dist -t $MAJOR
